### ISSUE TITLE
Code is incomplete

### ISSUE THREAD

**Issue by rodrigopiccelli** [biozal/dotnet-maui-cblite-learning-path#1]
Looks like the code on the master branch is incomplete.

**Comment by biozal** [comment]
It's because CB Lite doesn't support Maui yet.

**Comment by rodrigopiccelli** [comment]
ooooh, got it... was planning to use it instead of place json files on data folder... sad...

**Comment by biozal** [comment]
It's coming very soon.   Sent from my iPhoneOn Apr 1, 2023, at 4:18 PM, Rodrigo Bueno Piccelli ***@***.***> wrote:﻿
ooooh, got it... was planning to use it instead of place json files on data folder... sad...
